services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_spotify_clone_db
    environment:
      POSTGRES_DB: spotify_clone_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: