logging:
  level:
    ROOT: info
    org.hibernate.SQL: DEBUG
    com.jason.spotifycloneback: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: spotify-clone-back
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${postgres_url:localhost}:5432/${postgres_db:spotify_clone_db}
    username: ${postgres_username:username}
    password: ${postgres_password:password}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: spotify_clone
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  flyway:
    enabled: true #true by default
    default-schema: spotify_clone
server:
  port: 8080


okta:
  oauth2:
    issuer: https://jasoncat.eu.auth0.com/
    client-id: ${auth0_client_id}
    client-secret: ${auth0_client_secret}